### ISSUE TITLE
Latest build is can't connect to Mikrotik or?

### ISSUE THREAD

**Issue by SAOPP** [funkolab/cs-mikrotik-bouncer#1]
Hi!

I just saw it a repo moved and a new release of bouncer. Goin to upgrade my image from 19 of March, and faced with next behaviour:

That's my stack:
```
  crowdsec-bouncer-mikrotik:
    image: ghcr.io/tuxtof/cs-mikrotik-bouncer:latest-working
    container_name: crowdsec-bouncer-mikrotik
    networks:
      - proxy
    depends_on:
      - crowdsec
    environment:
      - TZ=Europe/Kiev
      - CROWDSEC_BOUNCER_API_KEY=${BOUNCER_MIKROTIK_API_KEY}
      - CROWDSEC_URL=http://crowdsec:8080/
      - MIKROTIK_HOST=${MIKROTIK_HOST}
      - MIKROTIK_USER=${MIKROTIK_API_ACCESS}
      - MIKROTIK_PASS=${MIKROTIK_API_ACCESS}
      - MIKROTIK_TLS=false
      - LOG_LEVEL=0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
```

After upgrade container (to `ghcr.io/funkolab/cs-mikrotik-bouncer:latest`) is loop restart every time, here is from container log:

```
{"level":"debug","time":"2022-05-21T17:06:00+03:00","message":"Using config: map[crowdsec_bouncer_api_key:76567b69177b455af74a227ae8a3fa43 crowdsec_url:http://crowdsec:8080/ log_level:0 mikrotik_host:192.168.0.1:8728 mikrotik_pass:pass mikrotik_tls:false mikrotik_user:user]"}
{"level":"info","time":"2022-05-21T17:06:00+03:00","message":"Connecting to mikrotik"}
{"level":"info","time":"2022-05-21T17:06:05+03:00","message":"fill 14844 entry in internal addrList\n"}
{"level":"info","time":"2022-05-21T17:06:00+03:00","message":"mikrotik ip list addr"}
{"level":"info","time":"2022-05-21T17:06:05+03:00","message":"mikrotik ipv6 list addr"}
{"level":"fatal","error":"from RouterOS device: no such command prefix","time":"2022-05-21T17:06:05+03:00","message":"address-list print failed"}
{"level":"debug","time":"2022-05-21T17:06:07+03:00","message":"Using config: map[crowdsec_bouncer_api_key:76567b69177b455af74a227ae8a3fa43 crowdsec_url:http://crowdsec:8080/ log_level:0 mikrotik_host:192.168.0.1:8728 mikrotik_pass:pass mikrotik_tls:false mikrotik_user:user]"}
{"level":"info","time":"2022-05-21T17:06:07+03:00","message":"Connecting to mikrotik"}
{"level":"info","time":"2022-05-21T17:06:07+03:00","message":"mikrotik ip list addr"}
{"level":"info","time":"2022-05-21T17:06:11+03:00","message":"fill 14844 entry in internal addrList\n"}
{"level":"info","time":"2022-05-21T17:06:11+03:00","message":"mikrotik ipv6 list addr"}
{"level":"fatal","error":"from RouterOS device: no such command prefix","time":"2022-05-21T17:06:11+03:00","message":"address-list print failed"}
{"level":"debug","time":"2022-05-21T17:06:13+03:00","message":"Using config: map[crowdsec_bouncer_api_key:76567b69177b455af74a227ae8a3fa43 crowdsec_url:http://crowdsec:8080/ log_level:0 mikrotik_host:192.168.0.1:8728 mikrotik_pass:pass mikrotik_tls:false mikrotik_user:user]"}
{"level":"info","time":"2022-05-21T17:06:13+03:00","message":"Connecting to mikrotik"}
{"level":"info","time":"2022-05-21T17:06:13+03:00","message":"mikrotik ip list addr"}
{"level":"info","time":"2022-05-21T17:06:18+03:00","message":"fill 14844 entry in internal addrList\n"}
{"level":"info","time":"2022-05-21T17:06:18+03:00","message":"mikrotik ipv6 list addr"}
{"level":"fatal","error":"from RouterOS device: no such command prefix","time":"2022-05-21T17:06:18+03:00","message":"address-list print failed"}
{"level":"debug","time":"2022-05-21T17:06:20+03:00","message":"Using config: map[crowdsec_bouncer_api_key:76567b69177b455af74a227ae8a3fa43 crowdsec_url:http://crowdsec:8080/ log_level:0 mikrotik_host:192.168.0.1:8728 mikrotik_pass:pass mikrotik_tls:false mikrotik_user:user]"}
```
So, what this mean: `{"level":"fatal","error":"from RouterOS device: no such command prefix","time":"2022-05-21T17:06:05+03:00","message":"address-list print failed"}`? - my routeros is `6.49.2` on all devices.

So I'm tagged latest working image from 19 of March, and use it now. Any suggestion what's happens? Btw, the same way on my second and third mikrotiks...
